#!/bin/bash

#create screen detail arrays
declare -a displayDevice
declare -a x1
declare -a y1
declare -a x2
declare -a y2

#get list of screens
INPUT=screens.cfg
IFS=','
[ ! -f $INPUT ] && { echo "$INPUT file not found"; exit 99; }
while read sname sdipslay sx1 sy1 sx2 sy2
do
	options+=("$sname")
	displayDevice+=("$sdisplay")
	x1+=("$sx1")
	y1+=("$sy1")
	x2+=("$sx2")
	y2+=("$sy2")
done < $INPUT

#TEST

echo ${x1[0]}
echo ${x1[1]}
echo ${x1[2]}

#TSET

#create menu
echo "SELECT SCREEN"
PS3='Please enter your choice: '
options+=("quit")
select opt in "${options[@]}"
do
	case $opt in
		"quit")
			echo "Goodbye"
			break
			;;
		*)
			echo "selection option $opt"
			echo "origin: ${x1[$REPLY-1]},${y1[$REPLY-1]}"
			echo "extent: ${x2[$REPLY-1]},${y2[$REPLY-1]}"
			;;
	esac
done
